### PR TITLE
Fixed VoxelBrushCommand assigning brush before event

### LINKED ISSUE #106: [BUG] /b e melt makes an air ball
**Describe the bug**
/B e smooth apparently makes an air ball

**Desktop (please complete the following information):**
 - Minecraft version: 1.19.3
 - Voxelsniper version: 8.4.0
 - Server/client software Paper

### PR DESCRIPTION
**Pull request by KevinDaGame**
This issue fixes #106 
The brush was being assigned before the event had even fired. Now a brush will be instantiated, then passed to the event, and only if the event is successful will it apply. Instantiating the brush if the player doesn't have permission is not a problem

### CODE REVIEW

File: VoxelSniperCore/src/main/java/com/github/kevindagame/snipe/Sniper.java [hunk 1]
```diff
@@ -148,7 +148,7 @@ private boolean handleSneakLeftClick(String toolId, SnipeData snipeData, SnipeAc
     }
 
 
-    public IBrush setBrush(String toolId, Class<? extends IBrush> brush) {
+    public IBrush setBrush(String toolId, IBrush brush) {
```
Comment (Lennart99) [inline VoxelSniperCore/src/main/java/com/github/kevindagame/snipe/Sniper.java:151]:
```suggestion
    public IBrush setBrush(String toolId, @NotNull IBrush brush) {
```

**Review by Lennart99 — APPROVED** [review]
LGTM, only one small suggestion
