### PR TITLE
#112: Fixed NPE when joining server without voxelsniper permissions

### LINKED ISSUE #112: [BUG] NullpointerException when joining without permission
**Describe the bug**
Voxelsniper throws a NPE when a player without op/permission joins the server.

**To Reproduce**
1. Install plugin
2. Join server while not having OP and not having any voxelsniper permission

**Expected behavior**
No exception being thrown by voxelsniper

**Screenshots**

**Desktop (please complete the following information):**
 - Minecraft version: 1.19.3 (from stacktrace)
 - Voxelsniper version: 8.4.2
 - Server/client software: AdvancedSlimePaper

### PR DESCRIPTION
**Pull request by Lennart99**
Closes #112

### CODE REVIEW

**Comment by Lennart99** [comment]
Also made some improvements in some places to check for brushes being null

File: VoxelSniperCore/src/main/java/com/github/kevindagame/voxelsniper/events/player/PlayerBrushSizeChangedEvent.java [hunk 1]
```diff
@@ -8,16 +8,18 @@
...
     private static final HandlerList<PlayerBrushSizeChangedEvent> handlers = new HandlerList<>();
     private final int oldSize;
     private final int newSize;
     private final String toolId;
-    private final IBrush brush;
+    private final @NotNull IBrush brush;
     private EventResult status;
 
-    public PlayerBrushSizeChangedEvent(IPlayer p, String toolId, IBrush brush, int oldSize, int newSize) {
+    public PlayerBrushSizeChangedEvent(IPlayer p, String toolId, @NotNull IBrush brush, int oldSize, int newSize) {
```
Comment (KevinDaGame) [inline VoxelSniperCore/src/main/java/com/github/kevindagame/voxelsniper/events/player/PlayerBrushSizeChangedEvent.java:22]: Can a player change the brush size if no brush is assigned (due to permissions)?

**Review by KevinDaGame — APPROVED** [review]

File: VoxelSniperCore/src/main/java/com/github/kevindagame/voxelsniper/events/player/PlayerBrushSizeChangedEvent.java (hunk 1 above)
Comment (Lennart99) [reply VoxelSniperCore/src/main/java/com/github/kevindagame/voxelsniper/events/player/PlayerBrushSizeChangedEvent.java:22]: I made sure the event only gets called when a brush is assigned, didn't make much sense to me to change the size (and call the event) when no brush is assigned.
